{% set version = "0.0.4" %}

package:
  name: ioos_qartod
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ioos_qartod/ioos_qartod-{{ version }}.tar.gz
  sha256: a7e2346d4b968f3259bf08c274fabb7a38a013eb1db71f172dbe08a1de7e47d5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - quantities
    - pyproj

test:
  imports:
    - ioos_qartod

about:
  home: https://pypi.python.org/pypi/ioos_qartod
  license_file: LICENSE.txt
  license: Apache-2.0
  summary: 'Collection of utilities, scripts and tests to assist in automated quality assurance'

extra:
  recipe-maintainers:
    - ocefpaf
