travis:
  secure:
    BINSTAR_TOKEN: on+3DXAPYOC4ZH9e1Og7Az0LM0D2dJl0NDKx46XR3xsVDf75EvN3tucyjNpeiWnjSF4caeHvMkzxNLJPjwmOe/o+ja+cJQj8NBRzC24BI9pPNDGXJ5dzaLljd1cIM6HLLWrF6efDCqlEVEFW2rYZvaIpUgwUNIh/lWrYOEzGg9/K8Z/qb5KBKuKZHPzskmgCr76UNwtZwNaN4CAvyhyw80zCNy7hf4yi8nv16dwdVg4RQvMfYGeXNEye132mdm2aYd79L9be8VjYfuj0QQMcKfumK/CzW7tAr4GbFR4M2drSoKgRiSwWjvzL9MG2sZ4oGdvNkigu4623QbfQ6EVVQGKHxEwf2FWMw7DUuE85DS8i6wA7Tyrr7DuHCJ40An6PSolT4YRZ6Acg5weO58QFPAS8jZt0bETzRxCo0KHE+cvLXVwVF5zGdZoTduUZyv4+fWYv7YIYJxywJv4qbPmVL1dllOjLR9jcE/Yk590/BWtFlcfTaPNYO+cZAhHQr0jggtEVfRRFmBoAV672/aAgPwESkRtbBHZ2YK9tW7QQ8+4U/OUb/idCZfOCFsoWIAveyhK+80YlR60xPioCUk9i4Ru9DYJ+jydndjNy0nnCV9GQ32K0DOOWfDI1vRx8Z+zb3TE09BFzyVaiOeq5THLzHUNajYqiWZqLCPAf58b0DL8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
