travis:
  secure:
    BINSTAR_TOKEN: ooXPG6KOAvY1QbWAi0qydZ9E1kD3GjGMwh9a6We9vXJdVq/9czmWQPAGBmTDbvMH/AGl3cybL5Ng3sOIFDTzOP0YpxgYPYqz9uX1Ivt9Jrbs0zrvsLq+korxzao9kDwdc3gxpaKbaFFVOYNA0pp872vV0s3L1WBnU8dEZEMq2vQC3DdXaU0L10owqRwaAtPNCQ+UbqNomkaB0jE3x/Pctf8Le3wRYc7r+YtcW3Eh42IKfI2/dI+cJKjKqjbvqpcjzuFedyWgEraOzL0ZQ+H7zmNN4dtBOPFsocDN5yJ2hs315RfOtjPuS5RlmIfCtudiHYOTlV8RK5OD71Xh7xoso+A3Dpn6Kj7hggDfH5s5fCYqBkIEwTxGAQxflT12q2lSL4XaXlIJ+CIlwX2dB2Ev5iB+G/m6KLQSwWebEzvxVqJ3G6MxlM4ovkgYrelAGDw96re97IGiikR9NMgM1kX519zdPa4J7V5yxls97NL/Dexh6OZ6iwp9QziE6+7IDqfeo7uUzZraKVk32dYj+sYzagZmb0PT+DNX+7pDjsARnJLvWUg+So3enN/oNlJCRqYt9GCT3J0/00epit6HfXcjtLj6Qp6RMK2Nt2lwj5KSpfgYxbQliHD1SkrgKLXadx/ETmy+jk9RqbO4nEQ33WQPH2YCSWxhMfv2ql3zzsbb/YI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
